-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.follows
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    follower_id uuid,
    followed_id uuid,
    CONSTRAINT follows_pkey PRIMARY KEY (id),
    CONSTRAINT follows_followed_id_fkey FOREIGN KEY (followed_id)
        REFERENCES public.profiles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id)
        REFERENCES public.profiles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.follows
    OWNER to postgres;

GRANT ALL ON TABLE public.follows TO anon;

GRANT ALL ON TABLE public.follows TO authenticated;

GRANT ALL ON TABLE public.follows TO postgres;

GRANT ALL ON TABLE public.follows TO service_role;
